---
title: "Client dbeaver"

format:
  html:
    highlight-style: zenburn
---


# Installer 

À partir de [Dbeaver community edition](https://dbeaver.io/download/)



```{=html}
<iframe width="780" height="500" src="https://dbeaver.io/download/" title="Dbeaver CE"></iframe>
```

# Survol


{{< fa brands youtube >}} [Explorer les possibilités du client](https://www.youtube.com/watch?v=qWhCmvg_Sqc)

::: {.callout-tip}

### Configurer une connexion

:::

- Onglet `Main`
  - Connect by `Host`, 
    - Host: `localhost`, 
    - Port: `5434` (ou un autre nombre exotique)
    - Database: bd_2023-24 
    - Décocher `Show all databases
  - Authentification: `Database Native`
    - Username: `username` (ENT)
    - Password: xxxxxxx  (ENT) 
    - Cocher `Save password` 
  - 

- Onglet `PostgreSQL`

- Onglet `SSH`
  - Cocher `Use SSH Tunnel`
  - Settings
    - Host/IP: localhost
    - Port 22
    - Username: `username` (ENT)
    - Password: xxxxxxx  (ENT) 
    - Cocher `Save credentials`
  - Jump servers
    - Jump #1 etu-pgsql.math.univ-paris-diderot.fr  username Password
    - Target localhost:22  username Password
  
# Utiliser une connexion

Double cliquer et saisir les mots de passe demandés.

# Définir et utiliser un *projet*


::: {.callout-warning}

Durant le semestre, un `projet` unique devrait suffire à vos besoins.

Utiliser un `projet` doit vous aider à organiser votre travail, en particulier à retrouver facilement les travaux des semaines précédentes. 

:::


## Connections

Vous devrez créer une connection avec le serveur au sein de votre projet. 
Vous pouvez en créer d'autres avec d'autres serveurs, possiblement un serveur PostGres 
hébergé sur votre propre machine. 

## Bookmarks/Signets

[Documentation sur les signets](https://github.com/dbeaver/dbeaver/wiki/Bookmarks)

::: {.callout-tip}

Vous pouvez créer des signets pour retrouver facilement les schémas sur lesquels vous travaillez, ou avez travaillé. 

:::

<!-- ## Dashboards/Tableaux de bord -->

## Diagrammes ER

`dbeaver` permet de faire un peu de rétro-ingénieurie et de visualiser (partiellement) un schéma. Outil utile quand on veut retoucher un schéma ou 
simplement le comprendre.

## Scripts 

- Un script pour chaque séance de TD/TP
- Nommer le script de façon utile (avec `rename`)
- Commenter le script
- Séparer les requêtes par des lignes blanches et une ligne de commentaire blanche `--    `
- Utiliser le reformattage pour rendre votre code plus lisible




# Renseignements utiles


[wiki](https://github.com/dbeaver/dbeaver/wiki)

