---
title: "Semaine 2"
subtitle: "Algèbre relationnelle et SQL"
editor: source
---

::: callout-important

-   Cours magistral en Amphi. 1 Olympe de Gouges 14h-15h30
-   TD/TP 2004-2005-2006 Étage 2 Sophie Germain 15h45-18h15
-   {{< fa cal >}} [Emploi du temps](https://edt.math.univ-paris-diderot.fr/#/parcours/miashs/l3)

:::

## Préparer

Requêtes du TD 1 [TD 1](/workshops/td1.html) 

## Cours magistral : diapositives

Reprise de 
[Introduction à l'algèbre relationnelle](/slides/SQL_0.html) 
au {{< fa hand-point-right >}} [renommage](/slides/SQL_0.html#/renommage){target="_blank"} jusqu'à [Exemples de requêtes](/slides/SQL_0.html#/exemples-de-requêtes) (sans aborder les jointures externes)


Puis nous aborderons le langage de requêtes SQL dans 
[SQL requêtes élémentaires](/slides/SQL_1.html)
jusqu'à [Syntaxe de la clause `WHERE`](/slides/SQL_1.html#/syntaxe-de-la-condition-where-...-suite-3)

## Exercices : TD/TP 1


Nous abordons avec les outils de l'algèbre relationnelle et de SQL les questions posées dans le `td1` :

[html](/workshops/td1.html)  [pdf](/workshops/td1.pdf)


## Travail personnel (optionnel)

- Essayer d'installer un [client](/computing-access.qmd) sur votre ordinateur personnel 
- Essayez d'établir une connexion `ssh`  entre votre ordinateur personnel et `etu-pgsql.math.univ-paris-diderot.fr` et depuis cette machine de vous connecter au serveur PostGres (par exemple via `psql -d bd_2023-24`)
- Essayez d'établir un tunnel `ssh` entre votre ordinateur personnel et `etu-pgsql.math.univ-paris-diderot.fr`, puis de vous connecter au serveur PostGres depuis le client installé sur votre machine

Essayer de finir le TD 1

Vous pouvez aussi vous entrainer sur annales :

[CC 1 2023-24](/exams/cc1-2023-10-27.html)

<br><br>

::: {style="font-size: 0.875em;"}
retour à [Agenda](/ "Agenda du cours") ⏎
:::
