---
title: "BD xxx : Normalisation II"
---

```{r}
#| include: false
#| echo: false
#| eval: false

library(DBI)
db <- dbConnect(RSQLite::SQLite(), dbname = "sql.sqlite")
knitr::opts_chunk$set(connection = "db")
```


#  Introduction

---

## Rappel : Propriétés d'une décomposition

-   Soit ${\mathcal A}$ un schéma de relation et $\Sigma$ un ensemble de
    DF sur ${\mathcal A}$.

-   Soit $\left\{{\mathcal A}_1,\dots, {\mathcal A}_k\right\}$ une
    décomposition du schéma ${\mathcal A}$
    $\text{${\mathcal A}_i\not=\emptyset$, $1\le i\le k$ et }{\mathcal A}= \bigcup_{i=1}^k {\mathcal A}_i$

-   On ne peut pas décomposer arbitrairement, toutes les décompositions
    ne sont pas intéressantes

-   Conditions pour une décomposition "raisonnable" :

    -   Décomposition sans perte d'information

    -   Décomposition [sans perte de dépendance fonctionnelle]{.alert}

---

# Projection d'un ensemble de dépendances fonctionnelles

---

## Projection d'un ensemble de DF

-   Soit ${\mathcal A}$ un schéma de relation (${\mathcal A}$ est un
    ensemble d'attributs) et $\Sigma$ un ensemble de DF sur
    ${\mathcal A}$

-   Soit ${\mathcal A}_1\subset{\mathcal A}$ un sous-ensemble
    d'attributs

-   **Définition**
    $${\color{blue}\pi^{}_{{\mathcal A}_1}(\Sigma)=\left\{ X\to Y \mid \Sigma\models X\to Y \text{ et } X,Y\subset{\mathcal A}_1\right\}}$$
    Autrement dit $\pi^{}_{{\mathcal A}_1}(\Sigma)$ est l'ensemble des
    DF de la forme $X\to Y$ impliquée par $\Sigma$ et telle que
    $X\subset{\mathcal A}_1$ et $Y\subset {\mathcal A}_1$

-   **Caractérisation :** si $X\subset {\mathcal A}_1$ on l'équivalence
    $$X\to Y \in \pi_{{\mathcal A}_1}(\Sigma) \iff Y\subset\left\{X\right\}^+\cap{\mathcal A}_1$$


---

## Exemple

-   ${\mathcal A}=\left\{A,B,C\right\}$ et
    $\Sigma=\left\{A\to B, B\to C, C\to A\right\}$

-   $\pi^{}_{\left\{A,B\right\}}(\Sigma)$ est équivalent à
    $\left\{A\to B, B\to A\right\}$


---

## Calcul de $\pi_{{\mathcal A}_1}(\Sigma)$ 

On calcule un ensemble de DF équivalent à $\pi_{{\mathcal A}_1}(\Sigma)$

::: block
**Algorithme** $P := \emptyset$\
pour tout $X\subset {\mathcal A}_1$ tel que $X\not=\emptyset$ et
$X\not={\mathcal A}_1$\
calculer $Y=X^+\cap{\mathcal A}_1$ et ajouter $X\to Y$ à $P$\
renvoyer $P$
:::

L'ensemble de DF obtenu est équivalent à $\pi_{{\mathcal A}_1}(\Sigma)$\
[Très coûteux !]{.alert} Le nombre de sous-ensembles $X$ considérés est
$2^{\#{\mathcal A}_1}-2$
:::

---

## Exemple

-   ${\mathcal A}=\left\{A,B,C,D,E\right\}$ et
    [$\Sigma=\left\{A\to C, BC\to D, AD\to E\right\}$]{.alert}

-   $\pi_{AC}(\Sigma)$ est équivalent à $\left\{A\to C\right\}$\
    car $\left\{A\right\}^+=\left\{A,C\right\}$ et
    $\left\{C\right\}^+=\left\{C\right\}$

-   $\pi_{ABD}(\Sigma)$ est équivalent à $\left\{AB\to D\right\}$\
    car $\left\{A\right\}^+=\left\{A,C\right\}$,
    $\left\{B\right\}^+=\left\{D\right\}$,
    $\left\{D\right\}^+=\left\{D\right\}$,
    $\left\{A,B\right\}^+=\left\{A,B,C,D,E\right\}$,
    $\left\{A,D\right\}^+=\left\{A,D,C,E\right\}$,
    $\left\{B,D\right\}^+=\left\{B,D\right\}$

-   $\pi_{ABCE}(\Sigma)$ est équivalent à
    $\left\{A\to C, AB \to CE, AE\to C, ABC\to E, ABE\to C\right\}$\
    $A^+=AC \quad B^+=B \quad C^+=C \quad E^+=E$\
    $AB^+=ABCDE \quad AC^+=AC \quad AE^+=AEC$\
    $BC^+=BCD \quad BE^+=BE \quad CE^+=CE$\
    $ABC^+=ABCDE \quad ABE^+=ABECD$\
    $BCE^+=BCED \quad ACE^+=ACE$

-   Simplification : $\pi_{ABCE}(\Sigma)$ équivaut à
    $\left\{A\to C, AB\to E\right\}$


---


# Décomposition sans perte de DF

---

##  Définition

-   Soit ${\mathcal A}$ un schéma de relation et $\Sigma$ un ensemble de
    DF sur ${\mathcal A}$.

-   Soit $\left\{{\mathcal A}_1,\dots, {\mathcal A}_k\right\}$ une
    décomposition du schéma ${\mathcal A}$
    $\text{${\mathcal A}_i\not=\emptyset$, $1\le i\le k$ et }{\mathcal A}= \bigcup_{i=1}^k {\mathcal A}_i$

::: block
Définition La décomposition
$\left\{{\mathcal A}_1,\dots, {\mathcal A}_k\right\}$ préserve $\Sigma$
si l'ensemble des dépendances fonctionnelles locales
$\bigcup_{i=1}^k \pi_{{\mathcal A}_i}(\Sigma)$ est équivalent à $\Sigma$
:::

Puisque $\Sigma$ implique
$\bigcup_{i=1}^k \pi_{{\mathcal A}_i}(\Sigma)$, la décomposition
préserve $\Sigma$ si et seulement si toutes les DF de $\Sigma$ sont
impliquées par les DF locales


---

## Algorithme

-   C'est une extension de l'algorithme de fermeture permet de tester si
    une décomposition est sans perte de DF (sans devoir calculer les
    $\pi_{{\mathcal A}_i}(\Sigma)$)

-   Soit $X\to Y$ une DF de $\Sigma$


---

## Algorithme pour tester si $X\to Y$ est impliquée par
$\bigcup_{i=1}^k \pi_{{\mathcal A}_i}(\Sigma)$

-   $Z := X$

```{verbatim}
tant que $Z$ change faire
    pour tout $i=1,\dots, k$ faire
        $Z:= Z \cup \bigl( (Z\cap {\mathcal A}_i)^+ \cap {\mathcal A}_i\bigr)$
    fin pour tout
fin tant que
```

-   Si $Y\not\subset Z$ la réponse est NON, sinon la réponse est OUI

---

## Exemple

-   ${\mathcal A}=\left\{A,B,C,D\right\}$,
    ${\mathcal A}_1=\left\{A,B\right\}$,
    ${\mathcal A}_2=\left\{B,C\right\}$,
    ${\mathcal A}_3=\left\{C,D\right\}$

-   $\Sigma=\left\{A\to B, B\to C, C\to D, D\to A\right\}$

-   Est-ce que la décomposition
    $\left\{{\mathcal A}_1,{\mathcal A}_2,{\mathcal A}_3\right\}$
    préserve $\Sigma$ ?

1.  Les DF locales impliquent $A\to B$, $B\to C$, $C\to D$ (elles sont
    DF locales)

2.  Est-ce que les DF locales impliquent $D\to A$ ?\
    Commencer avec $Z={\color{blue}\left\{D\right\}}$\
    $({\color{blue}\left\{D\right\}}\cap\left\{CD\right\})^+\cap\left\{CD\right\}=\left\{D\right\}^+\cap\left\{CD\right\}=\left\{DABC\right\}\cap\left\{CD\right\}=\left\{C\right\}$,
    [ajouter $C$]{.alert}\
    $({\color{blue}DC}\cap BC)^+\cap BC=C^+\cap BC=CDAB\cap BC=B$,
    [ajouter $B$]{.alert}\
    $({\color{blue}DCB}\cap AB)^+\cap AB=B^+\cap AB=BCDA \cap AB$,
    [ajouter $A$]{.alert}\
    $DCBA$ contient $A$ donc [$D\to A$ est préservé]{.alert}


---

## Exemple

-   ${\mathcal A}=\left\{Ville, CP, Rue, Numero\right\}$

-   $\Sigma=\left\{CP\to Ville, Ville\, Rue\, Numero\to CP\right\}$

-   ${\mathcal A}_1=\left\{Ville, CP\right\}$${\mathcal A}_2=\left\{Rue, Numero, CP\right\}$

-   Est-ce que la décomposition
    $\left\{{\mathcal A}_1,{\mathcal A}_2\right\}$ préserve $\Sigma$ ?

1.  $CP\to Ville$ est préservée car elle est locale à ${\mathcal A}_1$

2.  Est-ce que $Ville\, Rue\, Numero\to CP$ est préservée ?\
    $Z:=\left\{Ville, Rue, Numero\right\}$\
    $\bigl(Z\cap \left\{Ville, CP\right\}\bigr)^+\cap \left\{Ville, CP\right\}=\left\{Ville\right\}$,
    [rien à ajouter]{.alert}\
    $\bigl(Z\cap \left\{Rue, Numero, CP\right\}\bigr)^+\cap \left\{Rue, Numero, CP\right\}=\left\{Rue, Numero\right\}$,
    [rien à ajouter]{.alert}\
    Donc $Ville\, Rue\, Numero\to CP$ n'est pas préservée



# Fin

